package com.android.xjtu.wechat.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.android.xjtu.wechat.dao.Friend;
import com.android.xjtu.wechat.dao.Message;
import com.android.xjtu.wechat.dao.Session;

import com.android.xjtu.wechat.greendao.FriendDao;
import com.android.xjtu.wechat.greendao.MessageDao;
import com.android.xjtu.wechat.greendao.SessionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig sessionDaoConfig;

    private final FriendDao friendDao;
    private final MessageDao messageDao;
    private final SessionDao sessionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        sessionDaoConfig = daoConfigMap.get(SessionDao.class).clone();
        sessionDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        sessionDao = new SessionDao(sessionDaoConfig, this);

        registerDao(Friend.class, friendDao);
        registerDao(Message.class, messageDao);
        registerDao(Session.class, sessionDao);
    }
    
    public void clear() {
        friendDaoConfig.clearIdentityScope();
        messageDaoConfig.clearIdentityScope();
        sessionDaoConfig.clearIdentityScope();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public SessionDao getSessionDao() {
        return sessionDao;
    }

}
